FROM eclipse-temurin:17-alpine

RUN apt-get update

# setup systen group and user
RUN addgroup --system viva --gid 1001 && adduser --system devops --uid 1001 --ingroup viva

EXPOSE 8080

ARG JAR_FILE
ARG ENV

ENV nk=${ENV}


CMD [ "echo, jarfile: ${JAR_FILE}" ]

COPY ${JAR_FILE} rest-api-server.jar


# ENTRYPOINT ["java","-jar","/nk-poc.jar"]
ENTRYPOINT exec java -jar /rest-api-server.jar